apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sassapplication-stripe-secret-key
  namespace: storefront-devsaas
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: deepagent-aws
    kind: ClusterSecretStore
  target:
    name: app-env
    creationPolicy: Merge
  data:
    - secretKey: STRIPE_SECRET_KEY
      remoteRef:
        key: teams-dev/storefront-devsaas/STRIPE_SECRET_KEY
